-- drop table sold_details;
-- drop table refunds;
-- drop table details_shop_prices;
-- drop table orders_detail_types;
-- drop table sales;
-- drop table orders;
-- drop table customers;
-- drop table details;
-- drop table storage_cells;
-- drop table deliveries_detail_types;
-- drop table guarantees;
-- drop table detail_types;
-- drop table customs;
-- drop table deliveries;
-- drop table small_productions;
-- drop table shops;
-- drop table small_suppliers;
-- drop table dealers;
-- drop table firms;
-- drop table suppliers;

create table suppliers
(
    id integer generated by default on null as identity (start with 3000),
    name        varchar(255) not null,
    primary key (id)
);

create table firms
(
    id integer primary key references suppliers on delete cascade,
    website varchar(255) not null
);

create table dealers
(
    id integer primary key references suppliers on delete cascade,
    website   varchar(255) not null
);

create table small_suppliers
(
    id integer primary key references suppliers on delete cascade,
    phone_number      varchar(255) not null
);

create table shops
(
    id integer primary key references suppliers on delete cascade,
    address varchar(255) not null
);

create table small_productions
(
    id integer primary key references suppliers on delete cascade,
    website             varchar(255) not null
);

create table deliveries
(
    id integer generated by default on null as identity (start with 3000),
    supplier_id      integer not null references suppliers,
    discount_percent double precision not null,
    formation_date   date    not null,
    delivery_date    date,
    primary key (id)
);

create table customs
(
    delivery_id    integer primary key references deliveries,
    clearance_date date not null,
    tax_percent    double precision not null
);

create table detail_types
(
    id integer generated by default on null as identity (start with 3000),
    name           varchar(255) not null,
    primary key (id)
);

create table guarantees
(
    id integer generated by default on null as identity (start with 3000),
    supplier_id     integer not null references suppliers,
    detail_type_id  integer not null references detail_types,
    guarantee_months integer not null,
    primary key (id),
    unique (supplier_id, detail_type_id)
);

create table deliveries_detail_types
(
    delivery_id    integer references deliveries,
    detail_type_id integer references detail_types,
    supplier_price double precision not null,
    primary key (delivery_id, detail_type_id)
);

create table storage_cells
(
    id integer generated by default on null as identity (start with 3000),
    primary key (id)
);

create table details
(
    id integer generated by default on null as identity (start with 3000),
    detail_type_id integer not null references detail_types,
    delivery_id    integer not null references deliveries,
    cell_id        integer references storage_cells,
    primary key (id)
);

create table customers
(
    id integer generated by default on null as identity (start with 3000),
    name        varchar(255) not null,
    primary key (id)
);

create table orders
(
    id integer generated by default on null as identity (start with 3000),
    order_date  date not null,
    customer_id integer references customers,
    primary key (id)
);

create table sales
(
    id integer generated by default on null as identity (start with 3000),
    customer_id integer not null references customers,
    sale_date   date not null,
    order_id    integer references orders,
    primary key (id)
);

create table orders_detail_types
(
    order_id       integer references orders,
    detail_type_id integer references detail_types,
    amount         integer not null,
    primary key (order_id, detail_type_id)
);

create table details_shop_prices
(
    detail_type_id integer primary key references detail_types,
    shop_price     double precision not null
);

create table refunds
(
    detail_id            integer primary key references details,
    customer_refund_date date not null,
    supplier_refund_date date
);

create table sold_details
(
    detail_id integer unique references details,
    sale_id   integer references sales,
    primary key (detail_id, sale_id)
);